apiVersion: 1
datasources:
  - name: TimescaleDB
    type: postgres
    url: ${DATABASE_HOST}:${DATABASE_PORT}
    database: ${DATABASE_NAME}
    user: ${DATABASE_USER}
    secureJsonData:
      password: ${DATABASE_PASSWORD}
    jsonData:
      sslmode: "require"
      postgresVersion: 1400
      timescaledb: true