apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-producer
spec:
  replicas: {{ .Values.producer.replicaCount }}
  selector:
    matchLabels:
      app: pump-producer
  template:
    metadata:
      labels:
        app: pump-producer
    spec:
      containers:
        - name: producer
          image: {{ .Values.producer.image.repository }}:{{ .Values.producer.image.tag }}
          imagePullPolicy: {{ .Values.producer.image.pullPolicy }}
          env:
            - name: DATABASE__HOST
              value: {{ .Values.global.env.DATABASE__HOST | quote }}
            - name: DATABASE__NAME
              value: {{ .Values.global.env.DATABASE__NAME | quote }}
            - name: DATABASE__USER
              value: {{ .Values.global.env.DATABASE__USER | quote }}
            - name: DATABASE__PORT
              value: {{ .Values.global.env.DATABASE__PORT | quote }}
            - name: DATABASE__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.env.KUBERNETES__CREDENTIALS_SECRET_NAME }}
                  key: PATRONI_SUPERUSER_PASSWORD
            - name: PUMP__ID
              value: {{ .Values.global.env.PUMP__ID | quote }}
            - name: MONITORING__PROMETHEUS_PORT
              value: {{ .Values.global.env.MONITORING__PROMETHEUS_PORT | quote }}
            - name: MONITORING__FLASK_PORT
              value: {{ .Values.global.env.MONITORING__FLASK_PORT | quote }}
            - name: LOGGING__LEVEL
              value: {{ .Values.global.env.LOGGING__LEVEL | default "INFO" | quote }}
            - name: LOGGING__FORMAT
              value: {{ .Values.global.env.LOGGING__FORMAT | default "json" | quote }}
            - name: MONITORING__DEBUG
              value: {{ .Values.global.env.MONITORING__DEBUG | default "false" | quote }}
            - name: DATA__RETENTION_DAYS
              value: {{ .Values.global.env.DATA__RETENTION_DAYS | default "30" | quote }}
            - name: DATA__BACKUP_ENABLED
              value: {{ .Values.global.env.DATA__BACKUP_ENABLED | default "false" | quote }}
            - name: ENVIRONMENT__TYPE
              value: {{ .Values.global.env.ENVIRONMENT__TYPE | quote }}
          ports:
            - containerPort: {{ .Values.global.env.MONITORING__FLASK_PORT | default 8080 }}
            - containerPort: {{ .Values.global.env.MONITORING__PROMETHEUS_PORT | default 8000 }}
          resources:
            {{- toYaml .Values.producer.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-timescaledb
spec:
  selector:
    statefulset.kubernetes.io/pod-name: {{ .Release.Name }}-timescaledb-0
  ports:
    - protocol: TCP
      port: {{ .Values.global.env.DATABASE__PORT }}
      targetPort: {{ .Values.global.env.DATABASE__PORT }}
  type: ClusterIP